### PR TITLE
Clarify some formulations in the README.md file.

### PR DESCRIPTION
**Pull request by mmokrejs**
I find the documentation highly incomplete and only saying half of the truth. Here is some attempt to improve it a bit.

### CODE REVIEW

**Comment by jaredo** [comment]
I like your suggestions, except the phrase "Nextera Mate Pair linker" is not really used in official documentation (see below). I prefer to stick with "Nextera Mate Pair adapter" or "Nextera Mate Pair junction adapter".

https://www.illumina.com/documents/products/technotes/technote_nextera_matepair_data_processing.pdf

**Comment by jaredo** [comment]
Actually it does not remove P1/P2 adapters either.

**Comment by mmokrejs** [comment]
> "Nextera Mate Pair linker" is not really used in official documentation

I find the official documentation unclear. It should distinguish between adapter and linker, and especially trimming and **splitting** programs should take care about proper phrasing as the actions are very different. NxTrim as you explained me does only the splitting part, and assumes trimming was done prior to using NxTrim (it would be more complicated&slower to do afterwards due to the RF reads being reverse-complemented). Do you really object that much? ;-)

> Actually it does not remove P1/P2 adapters either.

So what is the TruSeq_Adapter aka IndexSP on https://github.com/sequencing/NxTrim/blob/master/matepair.cpp#L10 needed for?
And what is the TruSeq3/2 sequence at https://github.com/sequencing/NxTrim/blob/master/matepair.cpp#L11 needed for?

I assumed in both cases it is used to detect the left most end of Illumina adapter (to trim away rightwards from the start).

In both cases you are missing an A nucleotide which appears in the data because of the sticky end being introduced using Klenow fragment. Proper queries should be:

```
>TruSeq3/1 aka TruSeq_Adapter aka IndexSP
aGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
>TruSeq3/2
aGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTA
```

**Comment by jaredo** [comment]
>So what is the TruSeq_Adapter aka IndexSP on >https://github.com/sequencing/NxTrim/blob/master/matepair.cpp#L10 needed for?
>And what is the TruSeq3/2 sequence at >https://github.com/sequencing/NxTrim/blob/master/matepair.cpp#L11 needed for?

>I assumed in both cases it is used to detect the left most end of Illumina adapter (to trim away rightwards >from the start).

This code is actually to catch the case where the DNA fragment is less than 2x the readlength. This means that R1 can read into the external adapter on the other side of the fragment.

eg.
```
R1------------------------>
    AAAAAAAAAAAABBBB
```
where `BBBB` is the external adapter. NxTrim will (hopefully) see this and remove `BBBB` accordingly.  

This is an edge case that hopefully does not happen often but of course depends on sample preparation. In my data it is <0.5% of read pairs but your mileage may vary.

I agree that users should be able to specify their own adapters as arguments and will add some code for this.

**Comment by jaredo** [comment]
Thanks for your input, I have incorporated many of your suggestions in the current README.

**Pull request closed without merging**
